### ISSUE TITLE
Docs and instructions

### ISSUE THREAD

**Issue by weiliu620** [pandegroup/reaction_prediction_seq2seq#1]
Hi, 

I really like the paper but could not find a simple instruction to run the training routine. It seems most of the code and docs are forked from the seq2seq repository. Some additional folders seem related to the preprocessed data. 

Can I expect to have a minimalist document soon?

Thank you. This is great work.

**Comment by bowenliu16** [comment]
Hi,

Thanks for your message

I have updated the docs. Please ping me if you have any additional questions

Bowen

**Comment by weiliu620** [comment]
I followed the instruction, but got errors. Here is what I did: 

- Put the trained models in `model_working_directory`. 
- Change `train_options.json` file. I'm not sure what the vocabulary target and source means, so here is my file after change. 

```
{"model_params": {"vocab_target": "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/processed_data/vocab", "attention.class": "seq2seq.decoders.attention.AttentionLayerBahdanau", "embedding.dim": 512, "source.reverse": true, "source.max_seq_len": 140, "decoder.params": {"rnn_cell": {"dropout_input_keep_prob": 0.8, "dropout_output_keep_prob": 1.0, "cell_class": "LSTMCell", "num_layers": 4, "cell_params": {"num_units": 512}}, "max_decode_length": 140}, "attention.params": {"num_units": 512}, "embedding.share": true, "optimizer.name": "Adam", "encoder.params": {"rnn_cell": {"dropout_input_keep_prob": 0.8, "dropout_output_keep_prob": 1.0, "cell_class": "LSTMCell", "num_layers": 2, "cell_params": {"num_units": 512}}}, "decoder.class": "seq2seq.decoders.AttentionDecoder", "encoder.class": "seq2seq.encoders.BidirectionalRNNEncoder", "bridge.class": "seq2seq.models.bridges.ZeroBridge", "optimizer.learning_rate": 0.0001, "target.max_seq_len": 140, "vocab_source": "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/processed_data/vocab"}, "model_class": "AttentionSeq2Seq"}
```
run `bash google_seq2seq_infer_jul_5_2017_1_nobeam.sh ` under the home directory of git repository and got the errors: 

```
INFO:tensorflow:Creating ParallelTextInputPipeline in mode=infer
INFO:tensorflow:
ParallelTextInputPipeline:
  num_epochs: 1
  shuffle: false
  source_delimiter: ' '
  source_files: [/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/processed_data/test_sources]
  target_delimiter: ' '
  target_files: []

INFO:tensorflow:Creating AttentionSeq2Seq in mode=infer
INFO:tensorflow:
AttentionSeq2Seq:
  attention.class: seq2seq.decoders.attention.AttentionLayerBahdanau
  attention.params: {num_units: 512}
  bridge.class: seq2seq.models.bridges.ZeroBridge
  bridge.params: {}
  decoder.class: seq2seq.decoders.AttentionDecoder
  decoder.params:
    max_decode_length: 140
    rnn_cell:
      cell_class: LSTMCell
      cell_params: {num_units: 512}
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 4
  embedding.dim: 512
  embedding.share: true
  encoder.class: seq2seq.encoders.BidirectionalRNNEncoder
  encoder.params:
    rnn_cell:
      cell_class: LSTMCell
      cell_params: {num_units: 512}
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 2
  inference.beam_search.beam_width: 0
  inference.beam_search.choose_successors_fn: choose_top_k
  inference.beam_search.length_penalty_weight: 0.0
  optimizer.clip_gradients: 5.0
  optimizer.learning_rate: 0.0001
  optimizer.lr_decay_rate: 0.99
  optimizer.lr_decay_steps: 100
  optimizer.lr_decay_type: ''
  optimizer.lr_min_learning_rate: 1.0e-12
  optimizer.lr_staircase: false
  optimizer.lr_start_decay_at: 0
  optimizer.lr_stop_decay_at: 1000000000.0
  optimizer.name: Adam
  source.max_seq_len: 140
  source.reverse: true
  target.max_seq_len: 140
  vocab_source: /home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/processed_data/vocab
  vocab_target: /home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/processed_data/vocab

INFO:tensorflow:Creating DecodeText in mode=infer
INFO:tensorflow:
DecodeText: {delimiter: ' ', postproc_fn: '', unk_mapping: null, unk_replace: false}

INFO:tensorflow:Creating vocabulary lookup table of size 64
INFO:tensorflow:Creating vocabulary lookup table of size 64
INFO:tensorflow:Creating BidirectionalRNNEncoder in mode=infer
INFO:tensorflow:
BidirectionalRNNEncoder:
  rnn_cell:
    cell_class: LSTMCell
    cell_params: {num_units: 512}
    dropout_input_keep_prob: 0.8
    dropout_output_keep_prob: 1.0
    num_layers: 2
    residual_combiner: add
    residual_connections: false
    residual_dense: false

INFO:tensorflow:Creating AttentionLayerBahdanau in mode=infer
INFO:tensorflow:
AttentionLayerBahdanau: {num_units: 512}

INFO:tensorflow:Creating AttentionDecoder in mode=infer
INFO:tensorflow:
AttentionDecoder:
  max_decode_length: 140
  rnn_cell:
    cell_class: LSTMCell
    cell_params: {num_units: 512}
    dropout_input_keep_prob: 0.8
    dropout_output_keep_prob: 1.0
    num_layers: 4
    residual_combiner: add
    residual_connections: false
    residual_dense: false

INFO:tensorflow:Creating ZeroBridge in mode=infer
INFO:tensorflow:
ZeroBridge: {}

2018-03-14 12:02:54.157543: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-14 12:02:54.353794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 980 Ti major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 5.93GiB freeMemory: 5.22GiB
2018-03-14 12:02:54.353822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:03:00.0, compute capability: 5.2)
INFO:tensorflow:Restoring parameters from /home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/model_working_directory/jul_5_2017_1/model.ckpt-44001
2018-03-14 12:02:54.706416: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.706747: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.706749: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.706890: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.706978: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.707377: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.710792: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.710985: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_1/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.711200: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_1/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.711291: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_2/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.711993: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_3/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.712121: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_3/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.712529: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.712891: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_2/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.712991: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.713201: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/fw/extended_multi_rnn_cell/cell_1/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.713340: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.713557: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
2018-03-14 12:02:54.713971: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/bw/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.714070: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/bw/extended_multi_rnn_cell/cell_1/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.714123: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/fw/extended_multi_rnn_cell/cell_0/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.714466: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/fw/extended_multi_rnn_cell/cell_1/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.714550: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/bw/extended_multi_rnn_cell/cell_1/lstm_cell/kernel not found in checkpoint
2018-03-14 12:02:54.714685: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/fw/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
2018-03-14 12:02:54.714712: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key model/att_seq2seq/encode/bidi_rnn_encoder/bidirectional_rnn/bw/extended_multi_rnn_cell/cell_0/lstm_cell/kernel not found in checkpoint
Traceback (most recent call last):
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
	 [[Node: save/RestoreV2_15/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_58_save/RestoreV2_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weiliu/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/weiliu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/bin/infer.py", line 129, in <module>
    tf.app.run()
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/bin/infer.py", line 121, in main
    hooks=hooks) as sess:
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 673, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 493, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 851, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 856, in _create_session
    return self._sess_creator.create_session()
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 554, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 428, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    init_fn(sess)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 161, in <lambda>
    self._init_fn = lambda sess: init_fn(self, sess)
  File "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/bin/infer.py", line 114, in session_init_op
    saver.restore(sess, checkpoint_path)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
	 [[Node: save/RestoreV2_15/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_58_save/RestoreV2_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2_7', defined at:
  File "/home/weiliu/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/weiliu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/bin/infer.py", line 129, in <module>
    tf.app.run()
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/weiliu/projects/retrosyn/reaction_prediction_seq2seq/bin/infer.py", line 108, in main
    saver = tf.train.Saver()
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/weiliu/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key model/att_seq2seq/decode/attention_decoder/decoder/extended_multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
	 [[Node: save/RestoreV2_15/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_58_save/RestoreV2_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


```

What did I miss?

I'm on python 3.6, TF 1.4.1 (installed by Conda).

**Comment by weiliu620** [comment]
@bowenliu16 not sure you saw my message above. Appreciate your response.

**Comment by weiliu620** [comment]
Is this project being maintained now? This is great work, but I need to make sure it is maintained before investing more time. I'm studying the chemical structure-property relationship with machine learning methods, for oil and gas industry.

**Comment by bowenliu16** [comment]
I think your tensorflow version is not compatible with the seq2seq library. Try using version 1.0.1, and also python 3.5
You can do `pip install tensorflow-gpu==1.0.1` from within your conda environment
Let me know if this works

**Comment by weiliu620** [comment]
I'm able to run inference code with python 3.5 and TF 1.0.1. Thanks!

**Comment by huaiyi1996** [comment]
hello, i recently tried rework your job,but got some trouble with the
evaluation step.
When i tried to run the reaction_evaluation.ipynb  It just can't run
correctly.When i try to run it,it tells me that  true & false not the
keyword,but it's ok after i changed them with True & False.Then another
question coming,the .ipynb doesn't produce any result.I try to read the
code,find that the prediction_path has already been set up correctly.
So i turned to change it to the .py file to run,and i did it with
python3.5, but when i run .py again, i got new question .here is  my error
report


ImortError:/home/xxx/rdkit-Release_2016_09_4/lib/libRDBoost.so.1:undefined
symbol: _ZN5boost6python23throw_error_already_setEv

Thanks a lot for your great job at first.Hope for your reply~

Bowen Liu <notifications@github.com> 于 2018年1月31日周三 04:28写道：

**Comment by QuickLearner171998** [comment]
> I'm able to run inference code with python 3.5 and TF 1.0.1. Thanks!

Hi,
Did you change the vocab targe and source in the above JSON file?

On running the infer script with beam search and width=3 it gets stuck on the following message:
INFO:tensorflow:Restored model from /gdrive/My Drive/00_MY Projects and courses/reaction_prediction_seq2seq/model_working_directory/jul_5_2017_1/model.ckpt-44001

How much time did it take when you ran infer file.

thanks
